name: Share data between steps

on:
  workflow_dispatch:
    inputs:
      envUnderTest:
          description:
            'Select environment to run tests against.'
          required: true
          default: 'https://www.google.co.uk'

jobs:
  data-checks:
    runs-on: ubuntu-18.04
    steps:
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV

      - name: Add bespoke value
        id: step_one_point_five
        run: |
          pwd
          echo "PERCY_TOKEN=$PERCY_TOKEN" >> $GITHUB_ENV
        env:
          PUBLICATION_UNDER_TEST: ${{ github.event.inputs.envUnderTest }}

      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.action_state }}" # This will output 'yellow'
          echo "${{ env.PERCY_TOKEN }}"